name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Apply Patches
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./build-scripts/linux/apply-patches.sh $GITHUB_WORKSPACE

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.14.2
          extra: '-b http://ftp.jaist.ac.jp/pub/qtproject/'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake \
            -DDO_RELEASE_BUILD=ON \
            $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          make package

      - name: Upload Brewtarget Installers
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: brewtarget-linux-installers
          path: build/brewtarget*

      - name: Recover Debris Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: build
          retention-days: 2
