name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake \
            -DDO_RELEASE_BUILD=ON \
            $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          make package

      - name: Upload Brewtarget Installers
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: brewtarget-linux-installers
          path: build/brewtarget*

      # create an AppImage
      # resume here when I get the time:
      # https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html
      - name: Install App
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          make install DESTDIR=AppDir

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|qt-hello-world|latest|*x86_64.AppImage.zsync
        with:
          recipe: ${{github.workspace}}/build-scripts/linux/AppImageBuilder.yml

      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: AppImage

      - name: Recover Debris Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: build
